version: "3.9"
services:
  server:
    build: .
    restart: always
    ports:
    - 8086:8080
    depends_on: 
     - test-mysql
  test-mysql:
   hostname: test-mysql
   image: "mysql:5.7"
   restart: always
   ports:
    - 3306:3306
   environment:
    MYSQL_DATABASE: assurancedb
    MYSQL_USER: croff
    MYSQL_PASSWORD: croff
    MYSQL_ROOT_PASSWORD: croff